name: flutterhelloworld
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  go_router: ^14.0.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.5 # Актуальная версия BLoC
  equatable: ^2.0.5 # Для сравнения состояний
  shared_preferences: ^2.2.3 # Для локального хранилища
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.6.0
  barcode_scan2: ^4.2.4
  permission_handler: ^11.3.1
  fl_chart: ^0.68.0
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - images/